name: GitHub action prepare for pipeline in Python

on: 
  push:
    paths:
    - '**'

jobs:
  Default:
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@main
  
    ############# Prepare #############
   
    - name: Install powershell
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https
        wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install Python & twine
      run: |
        sudo apt-get update
        sudo apt-get install python
        sudo apt-get install python-pip
        pip install --upgrade pip
        pip install twine

    - name: verify install
      run: |
        which python
        pip show twine
      